name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install deps
        run: npm install

      - name: Build
        run: |
          npm run build
          npm run copy:package

  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Set NPM Token
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish new version
        run: 'echo Publish here'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
