# This is a basic workflow to help you get started with Actions

name: Version Bump and Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bump-version:
    # The type of runner that the job will run on
    name: "Bump version on master"
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2
        
      - name: Version bump
        uses: phips28/gh-action-bump-version@v8.0.18
        with:
          tag-prefix: release-
          major-wording: 'major'
          minor-wording: 'minor'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name:  Output
        env:
          NEW_TAG: ${{ steps.bump-version.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
        
  version:
    name: Create release
    runs-on: ubuntu-latest
    needs: [bump-version]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.bump-version.outputs.newTag }}
          release_name: Release ${{ steps.bump-version.outputs.newTag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
